CREATE DATABASE IF NOT EXISTS Flashcards DEFAULT CHARACTER SET utf8;

USE Flashcards;

DROP TABLE IF EXISTS Tags;
CREATE TABLE Tags(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Title VARCHAR(32) NOT NULL
);

DROP TABLE IF EXISTS Languages;
CREATE TABLE Languages(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Title VARCHAR(8) NOT NULL
);

DROP TABLE IF EXISTS Groups;
CREATE TABLE Groups(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	UserId INT NOT NULL,
	Title VARCHAR(64) NOT NULL,
	TimeCreated DATETIME NOT NULL,
	...
);

###
DROP TABLE IF EXISTS Tags;
CREATE TABLE Tags(
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Username VARCHAR(64) NOT NULL,
  Password VARCHAR(256) NOT NULL,
  UserTypeId INT NOT NULL,
  CONSTRAINT FkUsers_UserTypeId FOREIGN KEY (UserTypeId) REFERENCES UserTypes (Id) ON DELETE RESTRICT
);